#version: "3.8"

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: evrental-postgres
    environment:
      POSTGRES_DB: vehicle_rental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    networks:
      - evrental-net
#    command: >
#      postgres
#      -c shared_preload_libraries=postgis
#      -c max_connections=200
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: cache-db
    ports:
      - "6379:6379"
    networks:
      - evrental-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  evrental-net:
    driver: bridge
